### ISSUE TITLE
Crash when the earliest recorded date is the same day as now

### ISSUE THREAD

**Issue by jaoel** [lukors/time_track_cli#1]
**Repro steps:**

- Create a new time tracking database
- Add a new entry
- `tt log`

**Expected behavior:**
The program should not crash

**Actual behavior**
The program crashes

**Comment by lukors** [comment]
I'm unable to reproduce this bug.

I have fixed a bug that caused a crash when adding an entry to an empty database, maybe this is what you experienced? You can see if the latest version works for you: https://github.com/lukors/time_track_cli/releases/tag/v0.1.4

I'll close this issue, please re-open it if you still experience this bug in the latest version.
